# Generated by Django 6.1.1 on 2026-09-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dod',
            field=models.DateField(null=True),
        ),
    ]
