# Generated by Django 6.1.1 on 2026-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_alter_myuser_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(upload_to='meetups'),
        ),
    ]
